// 檔案位置：utils/themes.js

export const allThemes = [
  { id: 'theme-retro', name: '🕹️ 現代復古', desc: '結合像素藝術與高彩度霓虹，帶你回到 8-bit 的黃金年代。' },
  { id: 'theme-gray', name: '⚪ 靜默純灰', desc: '極簡主義的極致展現，用深淺不一的灰階打造專注無擾的學習空間。' },
  { id: 'theme-disney', name: '🏰 迪士尼', desc: '充滿夢幻與魔法的童話色彩，讓每個單字都像是一個奇妙的故事。' },
  { id: 'theme-african', name: '🦁 非洲狂野', desc: '奔放的暖色調與部落圖騰，感受來自大草原的原始生命力。' },
  { id: 'theme-mediterranean', name: '🌊 地中海', desc: '湛藍的海水與純白建築，帶來海風拂面的清新舒適感。' },
  { id: 'theme-fallout', name: '☢️ Fallout', desc: '核災末日後的生存者風格，帶著生鏽金屬與綠色螢光終端機的硬核科幻感。' },
  { id: 'theme-cyberpunk', name: '🌃 賽博龐克', desc: '霓虹交織的黑夜都會，充滿高科技與低端生活的未來叛逆氛圍。' },
  { id: 'theme-detective', name: '🕵️ 英國偵探', desc: '迷霧中的倫敦街頭，帶有煙斗、風衣與羊皮紙的懸疑推理氣息。' },
  { id: 'theme-provence', name: '🪻 普羅旺斯', desc: '漫山遍野的薰衣草紫，營造出南法鄉村的慵懶與浪漫。' },
  { id: 'theme-twilight', name: '🧛 暮光之城', desc: '幽暗森林與蒼白月光，帶有一絲神秘與唯美的吸血鬼浪漫。' },
  { id: 'theme-jjk', name: '🤞 咒術迴戰', desc: '領域展開！充滿咒力殘穢的強烈對比色，感受特級咒術師的魄力。' },
  { id: 'theme-demonslayer', name: '⚔️ 鬼滅之刃', desc: '呼吸法的華麗展現，融合大正時代的和風古典與熱血戰鬥氣息。' },
  { id: 'theme-chanel', name: '💎 香奈兒', desc: '經典黑白雙色搭配菱格紋質感，展現永恆不敗的優雅與奢華。' },
  { id: 'theme-aurora', name: '🌌 北歐極光', desc: '冰雪夜空中的絢麗光帶，帶來空靈且神秘的極地視覺饗宴。' },
  { id: 'theme-instagram', name: '📸 Instagram', desc: '熟悉漸層暖色調與圓角UI，打造最潮的社群打卡風格。' },
  { id: 'theme-egypt', name: '🏜️ 埃及', desc: '燦爛黃沙與神秘象形文字，重現法老王時代的輝煌與神秘。' },
  { id: 'theme-istanbul', name: '🕌 伊斯坦堡', desc: '橫跨歐亞的異國香料色彩，結合拜占庭與鄂圖曼的華麗圖騰。' },
  { id: 'theme-hepburn', name: '👗 奧黛麗赫本', desc: '經典的第凡內早餐藍與優雅黑白，散發復古好萊塢的迷人魅力。' },
  { id: 'theme-gatsby', name: '🥂 大亨小傳', desc: '1920年代的裝飾藝術風格，充滿幾何金線與極致奢華的派對氛圍。' },
  { id: 'theme-south', name: '🏡 美國南方', desc: '慵懶的爵士樂與鄉村木屋，帶有德州陽光與溫暖的復古色調。' },
  { id: 'theme-harrypotter', name: '🪄 哈利波特', desc: '魔法學校的羊皮紙與古典學院風，準備好你的魔杖與咒語。' },
  { id: 'theme-xmen', name: '✖️ X戰警', desc: '變種人的高科技戰甲風格，強烈的黃藍對比充滿英雄主義色彩。' },
  { id: 'theme-sakura', name: '🌸 日本櫻花', desc: '紛飛的粉紅櫻花瓣，帶有日式傳統與春日初綻的溫柔和煦。' },
  { id: 'theme-seto', name: '🏝️ 瀨戶內海', desc: '寧靜的島嶼風光與湛藍海水，享受日本鄉間的慢活與平靜。' },
  { id: 'theme-kyoto', name: '🍁 京都秋楓', desc: '古都的紅葉與千年古剎，充滿禪意與秋日微涼的懷舊風情。' },
  { id: 'theme-snow', name: '❄️ 日本冰雪', desc: '覆蓋白雪的合掌村與銀白世界，純淨無暇且寧靜的冬日氛圍。' },
  { id: 'theme-pokemon', name: '⚡ 寶可夢', desc: '成為寶可夢大師吧！充滿紅白精靈球與活潑童趣的冒險風格。' },
  { id: 'theme-animalcrossing', name: '🏕️ 動物之森', desc: '悠閒的無人島生活，充滿大自然綠意與可愛療癒的色彩。' },
  { id: 'theme-strawberry', name: '🍓 草莓大福', desc: '甜美可愛的粉白配色，像是一口咬下酸甜多汁的日式和菓子。' },
  { id: 'theme-destiny', name: '🐉 吞食天地', desc: '經典街機的三國群英風格，像素風的熱血戰鬥與懷舊記憶。' },
  { id: 'theme-aot', name: '⚔️ 進擊的巨人', desc: '獻出你的心臟！帶有高牆、立體機動裝置與調查兵團的壯烈氛圍。' },
  { id: 'theme-facebook', name: '👍 臉書風格', desc: '經典的FB藍白配色，給你最熟悉、最習慣的社交平台閱讀體驗。' },
  { id: 'theme-xianxia', name: '🗡️ 中國仙俠', desc: '雲霧繚繞的修仙境界，充滿水墨淡彩與御劍飛行的東方奇幻。' },
  { id: 'theme-ff7', name: '☄️ 太空戰士7', desc: '米德加的魔晄色彩，結合工業金屬與星球生命之流的史詩科幻。' },
  { id: 'theme-ff8', name: '🪶 太空戰士8', desc: '魔女與傭兵的浪漫交織，帶有羽毛與槍刃的唯美奇幻風格。' },
  { id: 'theme-ff13', name: '⚡ 太空戰士13', desc: '水晶神話的未來世界，充滿純潔白與高科技亮藍的俐落感。' },
  { id: 'theme-riverdale', name: '🍔 Riverdale', desc: '美式復古小鎮的霓虹燈與美式餐廳，暗藏懸疑與青春的強烈色彩。' },
  { id: 'theme-chipndale', name: '🐿️ 奇奇蒂蒂', desc: '橡果與森林的溫暖大地色系，充滿花栗鼠搗蛋活潑的歡樂氣氛。' },
  { id: 'theme-akihabara', name: '👾 秋葉原', desc: '御宅族的聖地！充滿女僕咖啡廳、動漫海報與電玩霓虹的熱鬧街頭。' },
  { id: 'theme-onomichi', name: '⛴️ 尾道小鎮', desc: '坂道、貓咪與瀨戶內海的交織，充滿日本文學與電影的懷舊感。' },
  { id: 'theme-starbucks', name: '☕ 星巴克', desc: '經典賽壬綠與木質調，彷彿能聞到咖啡香氣的質感文青空間。' },
  { id: 'theme-norwegian', name: '🌲 挪威的森林', desc: '幽暗深邃的北歐針葉林，帶有村上春樹式的孤寂與文學氣息。' },
  { id: 'theme-citypop', name: '🌇 City POP', desc: '80年代日本都會的繁華與浪漫，粉彩霓虹與敞篷車的復古流行。' },
  { id: 'theme-hungergames', name: '🏹 飢餓遊戲', desc: '燃燒的學仿鳥與施惠國的都城色彩，帶著生存戰鬥的緊繃與覺醒。' },
  { id: 'theme-taylor', name: '✨ 泰勒斯', desc: '閃耀的時代巡迴風格，充滿星光、吉他與流行音樂天后的多變魅力。' },
  { id: 'theme-shinichi', name: '⚽ 工藤新一', desc: '帝丹高中的青春色彩與偵探的理性冷靜，真相永遠只有一個。' },
  { id: 'theme-heiji', name: '🏍️ 服部平次', desc: '關西熱血男兒的爽朗與重機騎士的野性，充滿活力與自信的色調。' },
  { id: 'theme-kid', name: '🎩 怪盜基德', desc: '月光下的魔術師，純白西裝與單片眼鏡，華麗且優雅的神秘怪盜。' },
  { id: 'theme-haibara', name: '💊 灰原哀', desc: 'APTX4869 的神秘與冷靜理智的科學家氣息，隱藏著微溫的關懷。' },
  { id: 'theme-dragonball', name: '☄️ 七龍珠', desc: '尋找龍珠的熱血冒險！超級賽亞人的金黃怒氣與武道大會的激燃風格。' },
  { id: 'theme-ranma', name: '🐼 亂馬1/2', desc: '遇到冷水就會變身！充滿中華風與歡樂吵鬧的無厘頭色彩。' },
  { id: 'theme-shrine', name: '⛩️ 日本神社', desc: '鳥居的朱紅與神道教的莊嚴，充滿祈福、繪馬與神聖結界的靜謐感。' },
  { id: 'theme-zen', name: '🍵 日本禪宗', desc: '枯山水與抹茶的綠意，屏除一切雜念，達到身心合一的平靜學習境界。' }
];