-- 單字開心農場：同班短期借款。先執行既有開心農場 SQL，再於「新專案」執行本檔。
-- 本站以自訂 Cookie + anon key 登入，資料庫無法驗證 p_actor_id 是否為實際登入者；
-- 此函式確保正常操作的原子性與同班限制，但完整防冒用須先升級全站身分驗證。
BEGIN;

CREATE TABLE IF NOT EXISTS public.happy_farm_classmate_loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrower_id varchar(255) NOT NULL,
  lender_id varchar(255) NOT NULL,
  principal integer NOT NULL CHECK (principal IN (60, 100)),
  interest integer NOT NULL CHECK (interest >= 0),
  collateral_plot integer NOT NULL CHECK (collateral_plot >= 0),
  collateral_village text NOT NULL,
  sale_value integer NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'active', 'repaid', 'foreclosed', 'rejected', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  due_at timestamptz,
  closed_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS happy_farm_one_open_borrower_loan
  ON public.happy_farm_classmate_loans (borrower_id) WHERE status IN ('pending', 'active');
CREATE INDEX IF NOT EXISTS happy_farm_classmate_loans_lender_idx
  ON public.happy_farm_classmate_loans (lender_id, status);
ALTER TABLE public.happy_farm_classmate_loans ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.happy_farm_classmate_loans FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.happy_farm_loan_list(p_student_id text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(loan) ORDER BY loan.created_at DESC), '[]'::jsonb)
  FROM (SELECT id, borrower_id, lender_id, principal, interest, collateral_plot,
               collateral_village, sale_value, status, created_at, approved_at, due_at, closed_at
        FROM public.happy_farm_classmate_loans
        WHERE borrower_id = p_student_id OR lender_id = p_student_id
        ORDER BY created_at DESC LIMIT 30) loan;
$$;

CREATE OR REPLACE FUNCTION public.happy_farm_loan_action(
  p_actor_id text, p_action text, p_loan_id bigint DEFAULT NULL,
  p_target_id text DEFAULT NULL, p_amount integer DEFAULT NULL, p_plot_index integer DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_loan public.happy_farm_classmate_loans%ROWTYPE;
  v_borrower_id text;
  v_lender_id text;
  v_borrower_class text;
  v_lender_class text;
  v_borrower_farm jsonb;
  v_lender_farm jsonb;
  v_borrower_coins integer;
  v_lender_coins integer;
  v_due integer;
  v_surplus integer;
  v_village text;
  v_status text;
  v_detail text;
BEGIN
  IF p_actor_id IS NULL OR p_action NOT IN ('request', 'approve', 'reject', 'cancel', 'repay', 'foreclose') THEN
    RAISE EXCEPTION '借款操作無效';
  END IF;
  IF p_action = 'request' THEN
    IF p_target_id IS NULL OR p_target_id = p_actor_id OR p_amount NOT IN (60, 100) THEN
      RAISE EXCEPTION '請選擇同班出借者與 60 或 100 金幣';
    END IF;
    v_borrower_id := p_actor_id;
    v_lender_id := p_target_id;
  ELSE
    SELECT * INTO v_loan FROM public.happy_farm_classmate_loans WHERE id = p_loan_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION '找不到借款'; END IF;
    v_borrower_id := v_loan.borrower_id;
    v_lender_id := v_loan.lender_id;
    IF p_actor_id NOT IN (v_borrower_id, v_lender_id) THEN RAISE EXCEPTION '你不是借款當事人'; END IF;
  END IF;
  SELECT class_name INTO v_borrower_class FROM public.students WHERE student_id = v_borrower_id;
  SELECT class_name INTO v_lender_class FROM public.students WHERE student_id = v_lender_id;
  IF v_borrower_class IS NULL OR v_lender_class IS NULL OR v_borrower_class <> v_lender_class THEN
    RAISE EXCEPTION '只開放同班學生借款';
  END IF;
  PERFORM 1 FROM public.happy_farm_states
    WHERE student_id IN (v_borrower_id, v_lender_id) ORDER BY student_id FOR UPDATE;
  SELECT farm INTO v_borrower_farm FROM public.happy_farm_states WHERE student_id = v_borrower_id;
  SELECT farm INTO v_lender_farm FROM public.happy_farm_states WHERE student_id = v_lender_id;
  IF v_borrower_farm IS NULL OR v_lender_farm IS NULL THEN RAISE EXCEPTION '雙方都要先建立農場'; END IF;
  v_borrower_coins := coalesce((v_borrower_farm->>'coins')::integer, 0);
  v_lender_coins := coalesce((v_lender_farm->>'coins')::integer, 0);

  IF p_action = 'request' THEN
    IF p_plot_index IS NULL OR p_plot_index < 0 OR p_plot_index >= jsonb_array_length(v_borrower_farm->'plots')
       OR v_borrower_farm->'plots'->p_plot_index <> 'null'::jsonb THEN
      RAISE EXCEPTION '請選擇一塊空地作為抵押';
    END IF;
    v_village := v_borrower_farm->'plotVillages'->>p_plot_index;
    IF v_village IS NULL OR NOT (v_borrower_farm->'ownedVillages' ? v_village)
       OR (SELECT count(*) FROM jsonb_array_elements_text(v_borrower_farm->'plotVillages') AS elem(value) WHERE elem.value = v_village) < 2 THEN
      RAISE EXCEPTION '抵押地須為已購里別，且至少保留另一塊地';
    END IF;
    INSERT INTO public.happy_farm_classmate_loans
      (borrower_id, lender_id, principal, interest, collateral_plot, collateral_village, sale_value, status)
      VALUES (v_borrower_id, v_lender_id, p_amount, ceil(p_amount * 0.1)::integer,
              p_plot_index, v_village, p_amount + 60, 'pending') RETURNING * INTO v_loan;
    v_borrower_farm := jsonb_set(v_borrower_farm, ARRAY['plots', p_plot_index::text],
      jsonb_build_object('facility', 'loan_hold', 'loanId', v_loan.id));
    v_detail := '已送出借款申請，待同學同意後撥款；此地暫作抵押';
  ELSE
    IF (v_borrower_farm #>> ARRAY['plots', v_loan.collateral_plot::text, 'loanId']) IS DISTINCT FROM v_loan.id::text THEN
      RAISE EXCEPTION '抵押地狀態已改變，請聯絡管理者處理';
    END IF;
    IF p_action = 'approve' THEN
      IF p_actor_id <> v_lender_id OR v_loan.status <> 'pending' THEN RAISE EXCEPTION '只有出借者能同意待處理申請'; END IF;
      IF v_lender_coins < v_loan.principal + 12 THEN RAISE EXCEPTION '出借後須至少留下 12 金幣種苗金'; END IF;
      v_lender_farm := jsonb_set(v_lender_farm, '{coins}', to_jsonb(v_lender_coins - v_loan.principal));
      v_borrower_farm := jsonb_set(v_borrower_farm, '{coins}', to_jsonb(v_borrower_coins + v_loan.principal));
      UPDATE public.happy_farm_classmate_loans SET status = 'active', approved_at = now(), due_at = now() + interval '24 hours'
        WHERE id = v_loan.id;
      v_detail := '同學已撥款，24 小時內須償還本金及 10% 利息';
    ELSIF p_action IN ('cancel', 'reject') THEN
      IF v_loan.status <> 'pending' OR (p_action = 'cancel' AND p_actor_id <> v_borrower_id)
         OR (p_action = 'reject' AND p_actor_id <> v_lender_id) THEN RAISE EXCEPTION '無法撤銷此申請'; END IF;
      v_borrower_farm := jsonb_set(v_borrower_farm, ARRAY['plots', v_loan.collateral_plot::text], 'null'::jsonb);
      UPDATE public.happy_farm_classmate_loans SET status = CASE WHEN p_action = 'cancel' THEN 'cancelled' ELSE 'rejected' END,
        closed_at = now() WHERE id = v_loan.id;
      v_detail := '借款申請已結束，抵押地已解除';
    ELSE
      IF v_loan.status <> 'active' THEN RAISE EXCEPTION '這筆借款已結清'; END IF;
      v_due := v_loan.principal + v_loan.interest;
      IF now() >= v_loan.due_at THEN
        v_surplus := v_loan.sale_value - v_due;
        v_lender_farm := jsonb_set(v_lender_farm, '{coins}', to_jsonb(v_lender_coins + v_due));
        v_borrower_farm := jsonb_set(v_borrower_farm, '{coins}', to_jsonb(v_borrower_coins + v_surplus));
        v_borrower_farm := jsonb_set(v_borrower_farm, ARRAY['plots', v_loan.collateral_plot::text], 'null'::jsonb);
        v_borrower_farm := jsonb_set(v_borrower_farm, ARRAY['plotVillages', v_loan.collateral_plot::text], '"__foreclosed__"'::jsonb);
        UPDATE public.happy_farm_classmate_loans SET status = 'foreclosed', closed_at = now() WHERE id = v_loan.id;
        v_detail := format('逾期強制出售抵押地 %s 金幣；償還本金與利息 %s，餘款 %s 已返還借款者', v_loan.sale_value, v_due, v_surplus);
      ELSIF p_action = 'repay' AND p_actor_id = v_borrower_id THEN
        IF v_borrower_coins < v_due THEN RAISE EXCEPTION '目前金幣不足以一次還清 % 金幣', v_due; END IF;
        v_borrower_farm := jsonb_set(v_borrower_farm, '{coins}', to_jsonb(v_borrower_coins - v_due));
        v_lender_farm := jsonb_set(v_lender_farm, '{coins}', to_jsonb(v_lender_coins + v_due));
        v_borrower_farm := jsonb_set(v_borrower_farm, ARRAY['plots', v_loan.collateral_plot::text], 'null'::jsonb);
        UPDATE public.happy_farm_classmate_loans SET status = 'repaid', closed_at = now() WHERE id = v_loan.id;
        v_detail := format('已還清本金 %s 與利息 %s，抵押地已解除', v_loan.principal, v_loan.interest);
      ELSE
        RAISE EXCEPTION '尚未到期，或請由借款者還款';
      END IF;
    END IF;
  END IF;

  UPDATE public.happy_farm_states SET farm = v_borrower_farm, revision = revision + 1, updated_at = now()
    WHERE student_id = v_borrower_id;
  UPDATE public.happy_farm_states SET farm = v_lender_farm, revision = revision + 1, updated_at = now()
    WHERE student_id = v_lender_id;
  RETURN jsonb_build_object('loan_id', v_loan.id, 'detail', v_detail);
END $$;

REVOKE ALL ON FUNCTION public.happy_farm_loan_list(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.happy_farm_loan_action(text, text, bigint, text, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.happy_farm_loan_list(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.happy_farm_loan_action(text, text, bigint, text, integer, integer) TO anon, authenticated;
NOTIFY pgrst, 'reload schema';
COMMIT;
