-- 新專案 Supabase SQL Editor：本次異世界農莊擴充只需執行此檔一次。
-- 同班借款與互訪、導師班級單元權限；保留既有資料。
BEGIN;

-- 單字異世界悠閒農莊：同班借款。請在新專案 Supabase SQL Editor 執行一次。
-- 本站沿用自訂學生 Cookie + anon key，p_actor_id 無法由資料庫驗證；此函式維持交易原子性與同班限制。

CREATE TABLE IF NOT EXISTS public.isekai_farm_peer_loans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrower_id varchar(255) NOT NULL,
  lender_id varchar(255) NOT NULL,
  principal integer NOT NULL CHECK (principal IN (60, 100)),
  interest integer NOT NULL CHECK (interest >= 0),
  collateral_area text NOT NULL,
  sale_value integer NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'active', 'repaid', 'foreclosed', 'rejected', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  due_at timestamptz,
  closed_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS isekai_farm_one_open_borrower_loan
  ON public.isekai_farm_peer_loans (borrower_id) WHERE status IN ('pending', 'active');
CREATE INDEX IF NOT EXISTS isekai_farm_peer_loans_lender_idx ON public.isekai_farm_peer_loans (lender_id, status);
ALTER TABLE public.isekai_farm_peer_loans ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.isekai_farm_peer_loans FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.isekai_farm_loan_list(p_student_id text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(loan) ORDER BY loan.created_at DESC), '[]'::jsonb)
  FROM (SELECT id, borrower_id, lender_id, principal, interest, collateral_area,
               sale_value, status, created_at, approved_at, due_at, closed_at
        FROM public.isekai_farm_peer_loans
        WHERE borrower_id = p_student_id OR lender_id = p_student_id
        ORDER BY created_at DESC LIMIT 30) loan;
$$;

CREATE OR REPLACE FUNCTION public.isekai_farm_loan_action(
  p_actor_id text, p_action text, p_loan_id bigint DEFAULT NULL,
  p_target_id text DEFAULT NULL, p_amount integer DEFAULT NULL, p_area_id text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_loan public.isekai_farm_peer_loans%ROWTYPE;
  v_borrower_id text;
  v_lender_id text;
  v_borrower_class text;
  v_lender_class text;
  v_borrower_farm jsonb;
  v_lender_farm jsonb;
  v_borrower_coins integer;
  v_lender_coins integer;
  v_due integer;
  v_surplus integer;
  v_area_cost integer;
  v_detail text;
BEGIN
  IF p_actor_id IS NULL OR p_action NOT IN ('request','approve','reject','cancel','repay','foreclose') THEN
    RAISE EXCEPTION '借款操作無效';
  END IF;
  IF p_action = 'request' THEN
    IF p_target_id IS NULL OR p_target_id = p_actor_id OR p_amount NOT IN (60,100) OR p_area_id IS NULL THEN
      RAISE EXCEPTION '請選擇同班出借者、金額及抵押領地';
    END IF;
    v_borrower_id := p_actor_id; v_lender_id := p_target_id;
  ELSE
    SELECT * INTO v_loan FROM public.isekai_farm_peer_loans WHERE id = p_loan_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION '找不到借款'; END IF;
    v_borrower_id := v_loan.borrower_id; v_lender_id := v_loan.lender_id;
    IF p_actor_id NOT IN (v_borrower_id, v_lender_id) THEN RAISE EXCEPTION '你不是借款當事人'; END IF;
  END IF;
  SELECT class_name INTO v_borrower_class FROM public.students WHERE student_id = v_borrower_id;
  SELECT class_name INTO v_lender_class FROM public.students WHERE student_id = v_lender_id;
  IF v_borrower_class IS NULL OR v_lender_class IS NULL OR v_borrower_class <> v_lender_class THEN
    RAISE EXCEPTION '只開放同班學生借款';
  END IF;
  PERFORM 1 FROM public.isekai_farm_states WHERE student_id IN (v_borrower_id, v_lender_id) ORDER BY student_id FOR UPDATE;
  SELECT farm INTO v_borrower_farm FROM public.isekai_farm_states WHERE student_id = v_borrower_id;
  SELECT farm INTO v_lender_farm FROM public.isekai_farm_states WHERE student_id = v_lender_id;
  IF v_borrower_farm IS NULL OR v_lender_farm IS NULL THEN RAISE EXCEPTION '雙方都要先建立異世界農莊'; END IF;
  v_borrower_coins := coalesce((v_borrower_farm->>'coins')::integer,0);
  v_lender_coins := coalesce((v_lender_farm->>'coins')::integer,0);

  IF p_action = 'request' THEN
    IF NOT (v_borrower_farm->'unlockedAreas' ? p_area_id)
       OR jsonb_array_length(v_borrower_farm->'unlockedAreas') < 2
       OR p_area_id IN ('fittoa','ranoa','kingdragon')
       OR coalesce(v_borrower_farm #>> '{expansion,loanCollateral}','') <> '' THEN
      RAISE EXCEPTION '需以非起始、已開拓且未抵押的領地作擔保，並保留至少一塊領地';
    END IF;
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(v_borrower_farm->'plots'->p_area_id) AS plot(value)
               WHERE plot.value <> 'null'::jsonb) THEN RAISE EXCEPTION '抵押領地的六個田位必須全空'; END IF;
    v_area_cost := CASE p_area_id
      WHEN 'asura' THEN 105 WHEN 'riverland' THEN 145 WHEN 'foothills' THEN 180
      WHEN 'basherant' THEN 155 WHEN 'northern-ridge' THEN 195 WHEN 'east-wood' THEN 230
      WHEN 'shirone' THEN 190 WHEN 'sanakia' THEN 235 WHEN 'kikka' THEN 270 ELSE 0 END;
    IF v_area_cost < p_amount + ceil(p_amount * .1)::integer THEN RAISE EXCEPTION '抵押領地價值不足'; END IF;
    INSERT INTO public.isekai_farm_peer_loans
      (borrower_id,lender_id,principal,interest,collateral_area,sale_value,status)
      VALUES (v_borrower_id,v_lender_id,p_amount,ceil(p_amount * .1)::integer,p_area_id,v_area_cost,'pending') RETURNING * INTO v_loan;
    v_borrower_farm := jsonb_set(v_borrower_farm,'{expansion}',coalesce(v_borrower_farm->'expansion','{}'::jsonb) || jsonb_build_object('loanCollateral',p_area_id));
    v_detail := '已送出借款申請；空領地暫作抵押';
  ELSE
    IF (v_borrower_farm #>> '{expansion,loanCollateral}') IS DISTINCT FROM v_loan.collateral_area THEN
      RAISE EXCEPTION '抵押領地狀態已變更，請聯絡管理者';
    END IF;
    IF p_action = 'approve' THEN
      IF p_actor_id <> v_lender_id OR v_loan.status <> 'pending' THEN RAISE EXCEPTION '只有出借者能同意待處理申請'; END IF;
      IF v_lender_coins < v_loan.principal + 12 THEN RAISE EXCEPTION '出借後須至少留下 12 金幣'; END IF;
      v_lender_farm := jsonb_set(v_lender_farm,'{coins}',to_jsonb(v_lender_coins-v_loan.principal));
      v_borrower_farm := jsonb_set(v_borrower_farm,'{coins}',to_jsonb(v_borrower_coins+v_loan.principal));
      UPDATE public.isekai_farm_peer_loans SET status='active',approved_at=now(),due_at=now()+interval '6 hours' WHERE id=v_loan.id;
      v_detail := '同學已撥款；六小時內償還本金與 10% 利息';
    ELSIF p_action IN ('cancel','reject') THEN
      IF v_loan.status <> 'pending' OR (p_action='cancel' AND p_actor_id<>v_borrower_id)
         OR (p_action='reject' AND p_actor_id<>v_lender_id) THEN RAISE EXCEPTION '無法撤銷申請'; END IF;
      v_borrower_farm := jsonb_set(v_borrower_farm,'{expansion}',(v_borrower_farm->'expansion') - 'loanCollateral');
      UPDATE public.isekai_farm_peer_loans SET status=CASE WHEN p_action='cancel' THEN 'cancelled' ELSE 'rejected' END,
        closed_at=now() WHERE id=v_loan.id;
      v_detail := '申請已結束，抵押解除';
    ELSE
      IF v_loan.status <> 'active' THEN RAISE EXCEPTION '借款已結清'; END IF;
      v_due := v_loan.principal+v_loan.interest;
      IF now() >= v_loan.due_at THEN
        v_surplus := v_loan.sale_value-v_due;
        v_lender_farm := jsonb_set(v_lender_farm,'{coins}',to_jsonb(v_lender_coins+v_due));
        v_borrower_farm := jsonb_set(v_borrower_farm,'{coins}',to_jsonb(v_borrower_coins+v_surplus));
        v_borrower_farm := jsonb_set(v_borrower_farm,'{unlockedAreas}',
          (SELECT coalesce(jsonb_agg(value),'[]'::jsonb) FROM jsonb_array_elements_text(v_borrower_farm->'unlockedAreas') AS area(value)
           WHERE area.value <> v_loan.collateral_area));
        v_borrower_farm := jsonb_set(v_borrower_farm,'{expansion}',(v_borrower_farm->'expansion') - 'loanCollateral');
        IF v_borrower_farm->>'selectedArea' = v_loan.collateral_area THEN
          v_borrower_farm := jsonb_set(v_borrower_farm,'{selectedArea}','"fittoa"'::jsonb);
          v_borrower_farm := jsonb_set(v_borrower_farm,'{selectedRegion}','"west"'::jsonb);
        END IF;
        UPDATE public.isekai_farm_peer_loans SET status='foreclosed',closed_at=now() WHERE id=v_loan.id;
        v_detail := format('逾期出售抵押領地 %s 金幣；償還 %s，餘款 %s 還給借款者',v_loan.sale_value,v_due,v_surplus);
      ELSIF p_action='repay' AND p_actor_id=v_borrower_id THEN
        IF v_borrower_coins < v_due THEN RAISE EXCEPTION '金幣不足，需一次還清 %',v_due; END IF;
        v_borrower_farm := jsonb_set(v_borrower_farm,'{coins}',to_jsonb(v_borrower_coins-v_due));
        v_lender_farm := jsonb_set(v_lender_farm,'{coins}',to_jsonb(v_lender_coins+v_due));
        v_borrower_farm := jsonb_set(v_borrower_farm,'{expansion}',(v_borrower_farm->'expansion') - 'loanCollateral');
        UPDATE public.isekai_farm_peer_loans SET status='repaid',closed_at=now() WHERE id=v_loan.id;
        v_detail := '本金及利息已還清，領地解除抵押';
      ELSE RAISE EXCEPTION '借款未到期，或只有借款者能提前償還'; END IF;
    END IF;
  END IF;
  UPDATE public.isekai_farm_states SET farm=v_borrower_farm,revision=revision+1,updated_at=now() WHERE student_id=v_borrower_id;
  UPDATE public.isekai_farm_states SET farm=v_lender_farm,revision=revision+1,updated_at=now() WHERE student_id=v_lender_id;
  RETURN jsonb_build_object('loan_id',v_loan.id,'detail',v_detail);
END $$;

REVOKE ALL ON FUNCTION public.isekai_farm_loan_list(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.isekai_farm_loan_action(text,text,bigint,text,integer,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.isekai_farm_loan_list(text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.isekai_farm_loan_action(text,text,bigint,text,integer,text) TO anon,authenticated;

-- 同班互訪與取得少量收成；正常操作需在資料庫原子更新雙方存檔。
CREATE TABLE IF NOT EXISTS public.isekai_farm_visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id varchar(255) NOT NULL,
  target_id varchar(255) NOT NULL,
  action text NOT NULL CHECK (action IN ('visit','gather')),
  crop_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS isekai_farm_visits_actor_target_idx
  ON public.isekai_farm_visits (actor_id,target_id,action,created_at DESC);
ALTER TABLE public.isekai_farm_visits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.isekai_farm_visits FROM anon,authenticated;

CREATE OR REPLACE FUNCTION public.isekai_farm_visit_list(p_student_id text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(item) ORDER BY item.created_at DESC),'[]'::jsonb)
  FROM (SELECT actor_id,target_id,action,crop_id,created_at FROM public.isekai_farm_visits
        WHERE actor_id=p_student_id OR target_id=p_student_id ORDER BY created_at DESC LIMIT 30) item;
$$;

CREATE OR REPLACE FUNCTION public.isekai_farm_visit(
  p_actor_id text,p_target_id text,p_action text,p_crop_id text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_actor_class text; v_target_class text;
  v_actor_farm jsonb; v_target_farm jsonb;
  v_crop text; v_target_count integer; v_actor_count integer;
  v_detail text;
BEGIN
  IF p_actor_id IS NULL OR p_target_id IS NULL OR p_actor_id=p_target_id
     OR p_action NOT IN ('visit','gather') THEN RAISE EXCEPTION '互訪操作無效'; END IF;
  SELECT class_name INTO v_actor_class FROM public.students WHERE student_id=p_actor_id;
  SELECT class_name INTO v_target_class FROM public.students WHERE student_id=p_target_id;
  IF v_actor_class IS NULL OR v_target_class IS NULL OR v_actor_class<>v_target_class THEN
    RAISE EXCEPTION '僅能拜訪同班同學';
  END IF;
  IF p_action='gather' THEN
    PERFORM 1 FROM public.isekai_farm_states WHERE student_id IN (p_actor_id,p_target_id) ORDER BY student_id FOR UPDATE;
  END IF;
  SELECT farm INTO v_actor_farm FROM public.isekai_farm_states WHERE student_id=p_actor_id;
  SELECT farm INTO v_target_farm FROM public.isekai_farm_states WHERE student_id=p_target_id;
  IF v_actor_farm IS NULL OR v_target_farm IS NULL THEN RAISE EXCEPTION '雙方都需先建立農莊'; END IF;
  IF p_action='gather' THEN
    IF EXISTS (SELECT 1 FROM public.isekai_farm_visits
               WHERE actor_id=p_actor_id AND target_id=p_target_id AND action='gather'
                 AND created_at>now()-interval '3 hours') THEN
      RAISE EXCEPTION '對同一位同學每三小時只能取得一份收成';
    END IF;
    SELECT e.key INTO v_crop FROM jsonb_each_text(v_target_farm->'produce') AS e(key,value)
      WHERE e.value ~ '^[0-9]+$' AND e.value::integer>0
        AND (p_crop_id IS NULL OR e.key=p_crop_id) ORDER BY e.key LIMIT 1;
    IF v_crop IS NULL THEN RAISE EXCEPTION '同學目前沒有可取得的作物收成'; END IF;
    v_target_count := coalesce((v_target_farm->'produce'->>v_crop)::integer,0);
    v_actor_count := coalesce((v_actor_farm->'produce'->>v_crop)::integer,0);
    v_target_farm := jsonb_set(v_target_farm,ARRAY['produce',v_crop],to_jsonb(v_target_count-1));
    v_actor_farm := jsonb_set(v_actor_farm,ARRAY['produce',v_crop],to_jsonb(v_actor_count+1));
    UPDATE public.isekai_farm_states SET farm=v_actor_farm,revision=revision+1,updated_at=now() WHERE student_id=p_actor_id;
    UPDATE public.isekai_farm_states SET farm=v_target_farm,revision=revision+1,updated_at=now() WHERE student_id=p_target_id;
    v_detail := format('在同學農莊取得一份 %s；每三小時最多一次',v_crop);
  ELSE v_detail := '已拜訪同班同學的農莊';
  END IF;
  INSERT INTO public.isekai_farm_visits (actor_id,target_id,action,crop_id) VALUES (p_actor_id,p_target_id,p_action,v_crop);
  RETURN jsonb_build_object('detail',v_detail,'target_area',v_target_farm->>'selectedArea',
    'target_harvested',coalesce((v_target_farm->>'harvested')::integer,0),
    'target_produce',coalesce(v_target_farm->'produce','{}'::jsonb));
END $$;
REVOKE ALL ON FUNCTION public.isekai_farm_visit_list(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.isekai_farm_visit(text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.isekai_farm_visit_list(text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.isekai_farm_visit(text,text,text,text) TO anon,authenticated;

NOTIFY pgrst, 'reload schema';

-- 新專案 Supabase SQL Editor 執行一次。導師可獨立設定異世界農莊的可玩單元。
CREATE TABLE IF NOT EXISTS public.isekai_farm_lesson_access (
  class_name text PRIMARY KEY,
  mode text NOT NULL DEFAULT 'all' CHECK (mode IN ('all','allow','deny')),
  units jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(units)='array'),
  updated_by text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.isekai_farm_lesson_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isekai_farm_lesson_access_app ON public.isekai_farm_lesson_access;
CREATE POLICY isekai_farm_lesson_access_app ON public.isekai_farm_lesson_access
  FOR ALL TO anon,authenticated USING (true) WITH CHECK (true);
GRANT USAGE ON SCHEMA public TO anon,authenticated;
GRANT SELECT,INSERT,UPDATE ON public.isekai_farm_lesson_access TO anon,authenticated;
NOTIFY pgrst,'reload schema';

COMMIT;
